[package]
name = "bevy_jam_template"
version = "0.1.0"
edition = "2021"
default-run = "run"

[dependencies]
bevy = { version = "0.13", default-features = false, features = [
    # Core functionality
    "bevy_core_pipeline",
    "bevy_winit",
    "x11",
    "bevy_render",
    "bevy_asset",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "multi-threaded",
    "webgl2",

    # Extra functionality
    #bevy_gilrs",
    #serialize",
    "subpixel_glyph_atlas",
    #"bevy/tonemapping_luts",

    # File formats
    "png",
] }
bevy_asset_loader = { version = "0.20", features = ["2d", "progress_tracking"] }
bevy_common_assets = { version = "0.10", features = ["ron"] }
bevy_editor_pls = { version = "0.8", optional = true }
bevy_kira_audio = "0.19"
bevy_mod_debugdump = { version = "0.10", optional = true }
bevy_mod_picking = { version = "0.18", default-features = false, features = [
    "backend_bevy_ui",
] }
bevy_rapier2d = "0.25"
iyes_progress = "0.11"
lazy-regex = { version = "3", features = ["lite"] }
leafwing-input-manager = "0.13"
#noise = "0.8"
#rand = { version = "0.8", features = ["small_rng"] }
ron = "0.8"
serde = "1"
strum = { version = "0.26", features = ["derive"] }
tap = "1"

[features]
default = [
    "native_dev",
]
dev = [
    "dep:bevy_editor_pls",
    "bevy/dynamic_linking",
    "bevy_mod_picking/debug",
    "bevy_rapier2d/debug-render-2d",
]
native = [
    "bevy_rapier2d/parallel",
]
native_dev = [
    "native",
    "dev",
    "bevy/file_watcher",
    "bevy/embedded_watcher",
]
web = [
    "bevy_rapier2d/wasm-bindgen",
]
web_dev = [
    "web",
    "dev",
]
trace = [
    "bevy/trace",
    "bevy/wgpu_trace",
    "bevy/trace_tracy",
]
debug_dump = [
    "dep:bevy_mod_debugdump",
]

[[bin]]
name = "debug"
required-features = ["debug_dump"]
